# Generated by Django 2.0.2 on 2018-02-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180223_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(default='', max_length=130, unique=True)),
                ('submenu', models.ManyToManyField(to='blog.Category')),
            ],
        ),
    ]
