# Generated by Django 2.0.2 on 2018-02-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='submenu',
            field=models.ManyToManyField(blank=True, default='', null=True, to='blog.Category'),
        ),
    ]
