# Generated by Django 2.0.2 on 2018-05-02 12:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180502_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description_image',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', max_length=60000, verbose_name='Текст'),
        ),
    ]
