# Generated by Django 2.0.3 on 2018-05-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180504_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='submenu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
