# Generated by Django 2.0.5 on 2018-05-15 11:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180504_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержимое')),
                ('slug', models.CharField(max_length=50, verbose_name='URL')),
            ],
        ),
    ]
