# Generated by Django 2.0.5 on 2018-06-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.CharField(default='', max_length=20, verbose_name='Время на прочтение'),
        ),
    ]
