# Generated by Django 2.0.5 on 2018-06-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_post_read_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='is_published',
        ),
    ]
